project:
  type: website

website:
  title: "SuppawishSiri"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Post
        href: blog.qmd
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/suppawish11
format:
  html:
    theme: sketchy
    css: styles.css



